name: netbird
base: core22
summary: netbird
adopt-info: netbird
license: BSD-3-Clause
website: https://netbird.io/
source-code: https://github.com/ubuntu-robotics/netbird_snap
issues: https://github.com/ubuntu-robotics/netbird_snap/issues
contact: support@netbird.io
description: |
  NetBird combines a configuration-free peer-to-peer
  private network and a centralized access control
  system in a single platform, making it easy to create
  secure private networks for your organization or home.

  Quickstart:

  netbird up

  Additionally, one might provide additional arguments to the service-run:

    snap set netbird service-run-arguments="--log-level debug"


  NetBird log, config and socket files are stored in /var/snap/netbird/common
confinement: strict
architectures:
  - build-on: [amd64]
  - build-on: [arm64]
# - build-on: [riscv64]

layout:
  /etc/netbird:
    bind: $SNAP_COMMON
  /var/log/netbird:
    bind: $SNAP_COMMON/var/log/netbird
  /var/lib/netbird:
    bind: $SNAP_COMMON/var/lib/netbird
parts:
  netbird:
    plugin: go
    source: https://github.com/netbirdio/netbird.git
    source-tag: "v0.62.1"
    build-snaps: [go]
    build-packages:
      - libayatana-appindicator3-dev
      - libgl1-mesa-dev
      - libglx-dev
      - libx11-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - pkg-config
    override-pull: |
      craftctl default

      # Checkout latest tagged version
      git config --global --add safe.directory '*'
      # set version and grade from code
      version="$(git describe --always --tags| sed -e 's/^v//;y/-/./')"
      craftctl set version="$version"
      craftctl set grade="stable"
    override-build: |
      # Change default socket location
      for entry in client/cmd/root.go client/ui/client_ui.go; do
        sed -i "s|unix:///var/run/netbird.sock|unix:///var/snap/netbird/common/netbird.sock|" "$entry"
      done

      sed -i "s|development|$(craftctl get version)|" version/version.go

      craftctl default

      # Setup bash completion
      mkdir -p $CRAFT_PART_INSTALL/etc/bash_completion.d/
      $CRAFT_PART_INSTALL/bin/client completion bash > $CRAFT_PART_INSTALL/etc/bash_completion.d/snap.netbird
    organize:
      bin/client: bin/netbird
    stage:
      - bin/netbird
      - etc/bash_completion.d
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.bash': bin/
apps:
  netbird:
    command: bin/netbird
    completer: etc/bash_completion.d/snap.netbird
  service-run:
    command: bin/netbird_service_launcher.bash
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - ppp
