name: netbird
base: core22
summary: netbird
adopt-info: netbird
license: BSD-3-Clause
description: |
  Connect all the interfaces.
  Restart netbird.
  netbird.client up

grade: devel
confinement: strict

layout:
  /etc/netbird:
    bind: $SNAP_COMMON
  /var/log/netbird/client.log:
    bind-file: $SNAP_COMMON/client.log

parts:
  netbird:
    plugin: go
    source: https://github.com/netbirdio/netbird.git
    build-snaps: [go]
    build-packages:
      - libayatana-appindicator3-dev
      - libgl1-mesa-dev
      - libglx-dev
      - libx11-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - pkg-config
    override-pull: |
      craftctl default

      # set version and grade from code
      git config --global --add safe.directory '*'
      version="$(git describe --always --tags| sed -e 's/^v//;s/-/+git/;y/-/./')"
      [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
      craftctl set version="$version"
      craftctl set grade="$grade"
    override-build: |
      # Change default socket location
      for entry in client/cmd/root.go client/ui/client_ui.go; do
        sed -i "s|unix:///var/run/netbird.sock|unix:///var/snap/netbird/common/netbird.sock|" "$entry"
      done

      craftctl default

      # Setup bash completion
      mkdir -p $CRAFT_PART_INSTALL/etc/bash_completion.d/
      $CRAFT_PART_INSTALL/bin/client completion bash > $CRAFT_PART_INSTALL/etc/bash_completion.d/snap.netbird
    organize:
      bin/client: bin/netbird
    stage:
      - bin/netbird
      - etc/bash_completion.d

apps:
  netbird:
    command: bin/netbird
    completer: etc/bash_completion.d/snap.netbird

  service-run:
    command: bin/netbird service run
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - ppp

