name: netbird
base: core22
summary: netbird
adopt-info: netbird
description: |
  Connect all the interfaces.
  Restart netbird.
  netbird.client up

grade: devel
confinement: strict

parts:
  netbird:
    plugin: go
    source: https://github.com/netbirdio/netbird.git
    build-snaps: [go]
    build-packages:
      - libayatana-appindicator3-dev
      - libgl1-mesa-dev
      - libglx-dev
      - libx11-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - pkg-config
    override-pull: |
      craftctl default
      git config --global --add safe.directory '*'
      version="$(git describe --always --tags| sed -e 's/^v//;s/-/+git/;y/-/./')"
      [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
      craftctl set version="$version"
      craftctl set grade="$grade"

apps:
  client:
    command: bin/client --daemon-addr unix://$SNAP_DATA/netbird.sock --log-file $SNAP_DATA/client.log -c $SNAP_DATA/config.json

  service:
    command: bin/client service run --daemon-addr unix://$SNAP_DATA/netbird.sock --log-file $SNAP_DATA/client.log -c $SNAP_DATA/config.json
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - ppp

