name: Weekly builds

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snap-build:
    name: Remote build snaps
    runs-on: [ubuntu-latest]
    env:
      # snapcraft remote-build will create a repository with the name decided by the --build-id arg
      # URL to this repo echoed below to help debug builds (does not change if the workflow is re-run)
      SNAPCRAFT_BUILDER_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
      - name: Add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/provider/launchpad/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/provider/launchpad/credentials
          git config --global user.email "canonical-robotics-brand@canonical.com"
          git config --global user.name "Canonical robotics"
      - name: Print Launchpad build repository
        run: |
          echo "Building at: https://git.launchpad.net/~ce-certification-qa/+snap/$SNAPCRAFT_BUILDER_ID"
      - uses: snapcore/action-build@v1
        with:
          snapcraft-args: "remote-build --launchpad-accept-public-upload --build-id netbird-${SNAPCRAFT_BUILDER_ID}"
      - name: check number of built snaps
        run: |
          count_txt_files=$(find . -type f -name 'netbird_*.txt' | wc -l)
          count_snap_files=$(find . -type f -name 'netbird_*.snap' | wc -l)
          if [ "$count_txt_files" -ne "$count_snap_files" ]; then
            echo "Error: The number of '.txt' files and '.snap' files do not match."
            exit 1
          fi
      - uses: actions/upload-artifact@v3
        name: Upload snapcraft logs
        if: always()
        with:
          name: snapcraft_logs
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            netbird-*.txt
      - uses: actions/upload-artifact@v3
        name: Upload the snap as artifact
        with:
          name: netbird-snaps
          path: ./*.snap

  ros-publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [snap-build]
    strategy:
      matrix:
        architectures: [amd64, arm64]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: netbird-snaps
        path: .
    - name: Get snap filename
      run: echo "SNAPFILE=$(ls *${{ matrix.architectrues }}.snap)" >> $GITHUB_ENV
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ env.SNAPFILE }}
        release: edge