#!/bin/sh -e

# The layout for the log file/folder has changed.
# We thus make sure that existing logs are migrated to the new location
if [ -f "$SNAP_COMMON/client.log" ]; then
  mv "$SNAP_COMMON/client.log" "$SNAP_COMMON/var/log/netbird/."
fi
